apiVersion: v2
name: nebari-nebi-pack
description: A Helm chart for deploying Nebi (environment management platform) on Nebari
type: application
version: 0.1.4
appVersion: "0.15"
dependencies:
  - name: nebari-app
    repository: oci://quay.io/nebari/charts
    version: ">=0.1.1"
